# Generated by Django 6.1.1 on 2026-09-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KitEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_alunos_1_ao_5_ano', models.IntegerField(default=0)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.escola')),
            ],
        ),
    ]
